### ISSUE TITLE
Can't run bgtools after building

### ISSUE THREAD

**Issue by maij** [bigianb/bgda-explorer#19]
I can seemingly build the project using `./gradlew build` without any issue, but when I try to run it with `./gradlew run` I get the following error:

```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> No main class specified and classpath is not an executable jar.
```

How should the main class be specified?

I am running on Ubuntu 18.04 LTS.

**Comment by bigianb** [comment]
There are 2 projects in the repo: the java code and the c# code. The c# one you can open in visual studio and just run ... it will give you a nice UI where you can view files, view levels in 3d and export files.
The Java code is more about experimentation ... there are lots of small runnable classes. You would generally need to edit the main function to specify a file path and then run that particular file. For this I use intellij IDEA.
