### ISSUE TITLE
(Request) I'd like a chance to discuss this in discord if possible.

### ISSUE THREAD

**Issue by NuptupTDOW** [bigianb/bgda-explorer#25]
Myself and some others have been looking into the potential to recreate the Champions of Norrath and Return to Arms games using either unity or unreal, and so far, your explorer seems to be the most useful way to pull things out of the game that we could then import in to keep the classic look. We were wondering if you'd be interested in chatting about this idea in discord, so we can see how we can go about doing this with your help as well. Please feel free to reach out if you're interested. My discord I.D. is Nuptup#5402.

**Comment by bigianb** [comment]
I'd thought about this myself in the past but I could never figure out how to get unity or unreal to read the original assets. You would need to export them and import them ... which is fine when playing locally but you could never distribute what you create because the models are obviously copyright.

**Comment by NuptupTDOW** [comment]
Sorry for the late reply. 

For distribution I'd agree that it could never be sold or made a profit in any way, but I am not entirely sure about whether or not a no-profit fan project would have any issue being given to friends to play. It's something we still wanted to look into if we pursue this option.

However, the biggest question I have for you specifically is what all your explorer (this one or the java one) can and can't take from the game? The first question would be whether or not it can export the map files, and if so, what formats can it export them as?

Other than that, I figure if this ever does get any real traction, we could theoretically try to pull the assets and ai-upscale them before dumping them into the unreal engine directory.

**Comment by NuptupTDOW** [comment]
Looking into it a bit more, it seems as though we could attempt it, but pretty much if/when anyone with any claim to the IP has an issue with it, we'd have to pull it from online. But, assuming it's only ever held locally, it could work as a personal/small group project I think. And, if it ever starts looking like it'll be a fun thing to finish making, then we could theoretically disassociate it from the IP and make it as an "inspired by" title, using/commissioning new assets and going from there. But, to start off, it'd be really nice to have a somewhat visually pleasing set of stand-in assets to make the testing phases more enjoyable.
