### ISSUE TITLE
Any chance for a new release?

### ISSUE THREAD

**Issue by NuptupTDOW** [bigianb/bgda-explorer#26]
Hey there, I was wondering if the edits you made to the master branch since the last release could be compiled and pushed to a new release?

Thanks a bunch!

**Comment by NuptupTDOW** [comment]
Gonna go ahead and close this since it's not actually an "issue", but would still be nice when you get a chance :D

**Comment by bigianb** [comment]
I don’t have a windows pc right now … just macs. So I can’t do the compile.
You should be able to do it yourself though.
