### ISSUE TITLE
Is it possible to extract multiple items at once?

### ISSUE THREAD

**Issue by NuptupTDOW** [bigianb/bgda-explorer#27]
Hello, I was wanting to know if this tool has the ability to pull multiple models out at once with their accompanying materials/textures. Currently if I'm wanting to pull a model or texture I go individually for every item. But, with so many variant items, this is quickly becoming very time consuming. I was hoping to be able to do so, so that I can do a texture upscale attempt. 

Ideally, it'd be fantastic if I could just select a folder of items such as the "Gore Axe" folder, and export all models with textures and materials at once into a "Gore Axe" folder. But, I don't think this is currently possible.

I've also tried using a macro that just exports every single item one at a time, and changes the name by adding a 1 on the end, but that quickly crashed the app after about 50 exports. Would it be possible to have models and textures automatically be named by their ID in the browser when extracted instead of having a blank text field? This change paired with multi-export would make this much more efficient.

Again, thanks so much for this wonderful tool. I just wanted to post a potential improvement if it's possible to make happen.

**Comment by bigianb** [comment]
Try jbgda. I've made a jar with a little GUI here: https://github.com/bigianb/jbgda/releases/tag/v0.0.1-alpha
You'll need Java 20 installed. It should work on windows but I've only tested on Mac.

Mount the ISO and copy the files to the root dir shown in the GUI when you select the correct game. Hit extract and everything should extract.

Run it from the command line using something like:
java -jar jbgda.jar

You'll then see the output which will show you the files being extracted and also you'll see any errors. The UI doesn't have any error handling as it's a quick hack to get you going.
