### ISSUE TITLE
Inverted faces

### ISSUE THREAD

**Issue by nexuz6** [bigianb/bgda-explorer#3]
Hey!

I noticed that when i export a object and import it to blender (also unreal engine 4) some faces (surfaces) gets inverted.

So the models contain "holes" on a couple of places where the texture is displayed inside out. If i flip the face it fills the hole.

Am I making any sense? :)

Dwarf
![1-dwarf](https://cloud.githubusercontent.com/assets/7535429/8794606/5d584226-2f85-11e5-95a4-134847a8c45a.PNG)

Select faces that are inside out
![2-selected faces](https://cloud.githubusercontent.com/assets/7535429/8794607/5d58dcae-2f85-11e5-9d68-45cd814948c0.PNG)

Flipped faces
![3-flipped faces](https://cloud.githubusercontent.com/assets/7535429/8794608/5d5d464a-2f85-11e5-82ec-111521071798.PNG)

**Comment by bigianb** [comment]
That's right. The routine that the game uses in the PS2 does not do backface culling and so the models have no consistent winding order. I have thought about using the normal information to detect the outward pointing face of each triangle and setting the winding order as such, but never got the time. I'm not even sure it will work as I think some of the models assume double sided triangles. In something like blender you need to disable back-face culling to view the model properly.

**Comment by nexuz6** [comment]
Thanks for that quick response!
