### ISSUE TITLE
[XBOX] Justice League Heroes - lmp and vif files

### ISSUE THREAD

**Issue by Gnates** [bigianb/bgda-explorer#6]
Hi, I just recently heard about BGDA-Explorer. 
I would like to try out this tool, but I don't know how to compile. 
In the near future, will there be something available in the Releases section that I can use?

I'm trying to extract 3D models from Justice League Heroes [XBOX]. 
![Justice League Heroes 3D Model](https://thumbs.gfycat.com/ImmediateDopeyAegeancat-size_restricted.gif)
https://www.youtube.com/watch?v=dHsXNdaBHvo
I used QuickBMS to extract the contents from the .lmp files.
I've read that the .VIF files inside the .lmp files contain 3D meshes.
Can I use BGDA-Explorer to either view or convert the .VIF files to a 3D mesh format usable in Blender?
Or is there a different program that can do this?

**Comment by bigianb** [comment]
I can build a release ... may take a few days to figure out how and also a few days before I find time.
The thing is, this tool is specific to the PS2 versions of the games rather than xbox (I assume so at least ... I don't have the xobx versions). The VIF files are PS2 VIF streams and so are PS2 specific - I would not expect the xbox port to use such a format.
The explorer itself works with Dark Alliance and Champions of Norrath. Not sure about JLH ... never tried it. It may work but it also may need some tweaks.

**Comment by bigianb** [comment]
I've made a release. Let me know if it works.

**Comment by Gnates** [comment]
> The VIF files are PS2 VIF streams and so are PS2 specific - I would not expect the xbox port to use such a format.

Maybe I'm wrong and the game files I downloaded aren't for the Xbox version. I assumed it was xbox when I saw a default.xbe file among the other files.

> I've made a release. Let me know if it works.

Without making a changes to WorldExplorer, I tried to open a .lmp file but wasn't able to view the contents of it.
I then went into Tools, Settings, changed Engine Version from Dark Alliance 1 to Champions: Return to Arms, and now I can see the contents of the .lmp files.
I tried to select a random .vif file from the explorer tree, and then the program immediately crashes with:

> WorldExplorer has stopped working

Details:

> Problem signature:
>   Problem Event Name:	CLR20r3
>   Problem Signature 01:	WorldExplorer.exe
>   Problem Signature 02:	1.0.0.0
>   Problem Signature 03:	5cd8938f
>   Problem Signature 04:	WorldExplorer
>   Problem Signature 05:	1.0.0.0
>   Problem Signature 06:	5cd8938f
>   Problem Signature 07:	cc
>   Problem Signature 08:	113
>   Problem Signature 09:	System.NullReferenceException

Here is a sample of the lmp files I'm testing: https://www.sendspace.com/file/w6qfoz

**Comment by bigianb** [comment]
It would be weird for the xbox version to work. I'll see if I can find a cheap copy on ebay and look. I have the JLH PS2 disc somewhere which I can dig out and take a look.

**Comment by Gnates** [comment]
> It would be weird for the xbox version to work. I'll see if I can find a cheap copy on ebay and look. I have the JLH PS2 disc somewhere which I can dig out and take a look.

Do the sample files above contain any info about which game platform it is for? 
It's possible I maybe wrong and the files are specifically for the PS2.

I wasn't sure which game platform was easier to extract or had better quality 3D models and textures.

I was also considering using Ninja Ripper with an emulator if this method doesn't work out.

**Comment by Gnates** [comment]
@bigianb 
Thank you for taking the time to do this. I just noticed fixes for JLH in my notifications.
Will there be another release soon?
