### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by Gnates** [bigianb/bgda-explorer#8]
I forgot to mention I switched to Linux recently. 
I didn't get a chance to test the PS2 version of JLH before switching to Linux. 

I have the PS2 version now. 
Unfortunately, I didn't have much luck with running WorldExplorer in Wine or PlayOnLinux, but I did manage to get it to run in **VirtualBox**(Windows 7 64bit). However, I was only able to see the textures but not the 3D meshes in the 3D View. 
I think there are some limitations (OpenGL/DirectX?) with VirtualBox, maybe. 

I did try exporting the individual VIF models to OBJ, but viewing them in Blender showed them as non-existant objects, and the OBJ file size was around 80 bytes. 

Is there a proper way to run BGDA-Explorer/WorldExplorer in Linux? 
Or are there recommended components (VisualC++, VisualBasic, d3d9, corefonts, etc.) I should install with Wine? 
https://linuxconfig.org/images/winetricks-dll.png
https://linuxconfig.org/images/bnet-winetricks-vcrun-ubuntu-18.04.jpg

**Comment by Gnates** [comment]
I think I managed to get the program running in Lutris.
- Switched to 64bit Prefix and Proton 4.2
- I needed to install dotnet4.6

Viewing textures are fine: https://i.imgur.com/hltiJZc.png
Can't view the VIF models: https://i.imgur.com/80gd38Q.png
Unable to export model as OBJ.
- Using WorldExplorer_0.0.1
- https://github.com/bigianb/bgda-explorer/releases/download/0.0.1/WorldExplorer_0.0.1.zip


You can examine the Huntress LMP archive (PlayStation2) here: 
- https://files.catbox.moe/ohq44c.zip
- Let me know if the download is broken

**Comment by bigianb** [comment]
Nice getting it running under linux. I see the same under the latest windows version as you so it looks like there is some difference in the vif file format. I'll take a look but can't promise when.
