### ISSUE TITLE
Justice League Heroes - PSP Support?

### ISSUE THREAD

**Issue by Gnates** [bigianb/bgda-explorer#9]
There are some Justice League Heroes characters that were made exclusive to the **PSP** version of the game. For example:
**Supergirl** - supergrl.lmp
**Black Canary** - bcanary.lmp 
![Justice League Heroes - PSP Characters](https://images2.imgbox.com/99/a5/ucdbeYD2_o.png) https://images2.imgbox.com/99/a5/ucdbeYD2_o.png

Will it be possible to add PSP support in the future?

Again, thank you for all the work you've done.

**Comment by bigianb** [comment]
My guess is that the PSP file are a different format. I mean you can try them and you may be lucky .. but I doubt it. All the code here is very PS2 specific (the files are basically dumps of the DMA packets which the PS2 sends to the GS chip).
